package baocaojava;

import DAO.ChiTietPhieuNhapDAO;
import controller.PhieuNhapController;
import controller.SanPhamController;
import java.awt.HeadlessException;
import java.sql.Timestamp;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.ChiTieuPhieumodel;
import model.phieuModel;
import model.sanpham;

/**
 *
 * @author Toan
 */
public class NhapHangJpane extends javax.swing.JPanel {

    SanPhamController sanPhamController;
    DefaultTableModel bangSP;
    DefaultTableModel bangPN;
    PhieuNhapController phieuNhapController;
    phieuModel phiModel;
    ChiTieuPhieumodel chiTieuPhieumodel;
    public static double tongTien = 0;

    /**
     * Creates new form NhapHangJpane
     */
    public NhapHangJpane() {
        initComponents();
        bangSP = new DefaultTableModel();
        sanPhamController = new SanPhamController();
        phieuNhapController = new PhieuNhapController();
        chiTieuPhieumodel = new ChiTieuPhieumodel();
        phiModel = new phieuModel();
        jTable1.setModel(bangSP);
        bangSP.addColumn("Mã sữa");
        bangSP.addColumn("Tên Sữa");
        bangSP.addColumn("Số lượng");
        bangSP.addColumn("Đơn giá");
        loadDataToTable();
        loadNhaCungCapToComboBox();
        bangPN = new DefaultTableModel();
        jTable2.setModel(bangPN);
        bangPN.addColumn("STT");
        bangPN.addColumn("Mã sữa");
        bangPN.addColumn("Tên Sữa");
        bangPN.addColumn("Số lượng");
        bangPN.addColumn("Đơn giá");
        maPhieuTextField.setText(CreatId());
        nguoiTaoPhieuTextField.setText("toan");

    }

    private void loadNhaCungCapToComboBox() {
        sanPhamController = new SanPhamController();
        ArrayList<String> tenNCCList = sanPhamController.LayTenNcc();
        for (String tenNCC : tenNCCList) {
            nhaCungCapcbx.addItem(tenNCC);
        }
    }

    private void loadDataToTable() {
        bangSP.setRowCount(0);
        ArrayList<sanpham> list = sanPhamController.selectAll();
        for (sanpham sp : list) {
            bangSP.addRow(new Object[]{
                sp.getMaSua(),
                sp.getTenSua(),
                sp.getSoLuong(),
                sp.getDonGia(),});

        }
    }

    public String CreatId() {
        phieuNhapController = new PhieuNhapController();
        ArrayList<phieuModel> arr = phieuNhapController.selectAll();
        String check = "";
        int id = arr.size() + 1;
        if (arr != null) {
            for (phieuModel nhanVienmodel : arr) {
                if (nhanVienmodel.getMaPN().equals("PN" + id)) {
                    check = nhanVienmodel.getMaPN();
                }
            }
            while (check.length() != 0) {
                id++;
                for (int i = 0; i <= arr.size(); i++) {
                    if (arr.get(i).getMaPN().equals("NV" + id)) {
                        check = arr.get(i).getMaPN();
                    } else {
                        check = "";
                    }
                }
            }
            return "PN" + id;
        } else {
            return "PN" + 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        timKiemTextField = new javax.swing.JTextField();
        timKiembtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        maPhieuTextField = new javax.swing.JTextField();
        nguoiTaoPhieuTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nhaCungCapcbx = new javax.swing.JComboBox<>();

        setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        timKiembtn.setText("Làm mới");
        timKiembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiembtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(timKiemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(timKiembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timKiemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKiembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setText("Số lượng");

        jButton1.setText("THêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Mã phiếu");

        jLabel4.setText("Người tạo phiếu");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton2.setText("jButton2");

        jButton3.setText("Xóa sản phẩm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Tổng tiền:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("0đ");

        jButton4.setText("Nhập hàng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nhà cung cấp:");

        nhaCungCapcbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhaCungCapcbxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(462, 462, 462)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(76, 76, 76)
                                        .addComponent(jButton3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(277, 277, 277)
                                        .addComponent(jButton4))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel7))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(maPhieuTextField)
                                    .addComponent(nguoiTaoPhieuTextField)
                                    .addComponent(nhaCungCapcbx, 0, 390, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(maPhieuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(nhaCungCapcbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nguoiTaoPhieuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jButton4))
                .addGap(0, 56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow(); // Lấy hàng được chọn từ jTable1
        if (row != -1) {
            // Lấy thông tin sản phẩm từ jTable1
            String maSua = (String) bangSP.getValueAt(row, 0);
            String tenSua = (String) bangSP.getValueAt(row, 1);
            double donGia = (double) bangSP.getValueAt(row, 3);

            // Lấy số lượng từ jSpinner1
            int soLuong = (int) jSpinner1.getValue();

            // Tạo STT tự động
            int stt = bangPN.getRowCount() + 1;

            // Thêm dòng vào jTable2
            bangPN.addRow(new Object[]{stt, maSua, tenSua, soLuong, donGia});

            // Tính tổng tiền cho sản phẩm vừa thêm
            double tongTien = soLuong * donGia;

            // Cập nhật tổng tiền vào một JLabel hoặc JTextField
            double currentTotal = Double.parseDouble(jLabel6.getText().replace("đ", "").trim());
            currentTotal += tongTien;

            // Cập nhật lại hiển thị tổng tiền
            jLabel6.setText(currentTotal + "đ");
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một sản phẩm để thêm.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int row = jTable2.getSelectedRow();
        if (row != -1) {
            // Lấy số lượng và đơn giá của sản phẩm sẽ xóa
            int soLuong = (int) bangPN.getValueAt(row, 3);
            double donGia = (double) bangPN.getValueAt(row, 4);

            // Tính tổng tiền của sản phẩm sẽ xóa
            double tongTienXoa = soLuong * donGia;

            // Cập nhật tổng tiền
            double currentTotal = Double.parseDouble(jLabel6.getText().replace("đ", "").trim());
            currentTotal -= tongTienXoa;

            // Xóa dòng khỏi jTable2
            bangPN.removeRow(row);

            // Cập nhật lại hiển thị tổng tiền
            jLabel6.setText(currentTotal + "đ");
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm để xóa.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nhaCungCapcbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhaCungCapcbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nhaCungCapcbxActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        phiModel.setMaPN(maPhieuTextField.getText());
        phiModel.setNguoiTao(nguoiTaoPhieuTextField.getText());
        phiModel.setMaNCC((String) nhaCungCapcbx.getSelectedItem());
        // Lấy giá trị từ JLabel tổng tiền
        String tongTienText = jLabel6.getText();
        // Loại bỏ ký tự "đ" và khoảng trắng
        tongTienText = tongTienText.replace("đ", "").trim();
        // Chuyển đổi chuỗi thành double
        double tongTien = Double.parseDouble(tongTienText);
        phiModel.setTongTien(tongTien);
        phiModel.setThoiGianTao(new Timestamp(System.currentTimeMillis())); // Thiết lập thời gian hiện tại
        // Gọi controller để thêm phiếu
        try {
            phieuNhapController.themPhieu(phiModel);
            JOptionPane.showMessageDialog(this, "Thêm phiếu thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Thêm phiếu thất bại: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        ChiTietPhieuNhapDAO dao = new ChiTietPhieuNhapDAO(); // Tạo đối tượng DAO

        for (int row = 0; row < jTable2.getRowCount(); row++) {
            String maPN = maPhieuTextField.getText();
            String maSua = jTable2.getValueAt(row, 1).toString();
            int soLuong = Integer.parseInt(jTable2.getValueAt(row, 3).toString());
            double donGia = Double.parseDouble(jTable2.getValueAt(row, 4).toString());

            // Tạo đối tượng ChiTieuPhieumodel
            ChiTieuPhieumodel chiTietPhieu = new ChiTieuPhieumodel(maPN, maSua, soLuong, donGia);

            // Gọi phương thức thêm vào cơ sở dữ liệu
            int ketQua = dao.them(chiTietPhieu);
            if (ketQua > 0) {
                System.out.println("Thêm thành công cho dòng: " + row);
            } else {
                System.out.println("Thêm không thành công cho dòng: " + row);
            }
        }
        loadDataToTable();


    }//GEN-LAST:event_jButton4ActionPerformed

    private void timKiembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiembtnActionPerformed
        // TODO add your handling code here:
        String name = timKiemTextField.getText(); // Giả sử name là "Toàn"
        String condition = "LOWER(TenSua) LIKE LOWER('%" + name + "%')";

        ArrayList<sanpham> nhanVienmodels = null;
        if (name.trim().length() == 0) {
            nhanVienmodels =sanPhamController.selectAll();
        } else {
            nhanVienmodels = sanPhamController.seLectByCondition(condition);
        }

        // Xóa dữ liệu cũ trên bảng
        bangSP.setRowCount(0);

        // Tải dữ liệu vào bảng
        for (sanpham sp : nhanVienmodels) {
            bangSP.addRow(new Object[]{
                sp.getMaSua(),
                sp.getTenSua(),
                sp.getSoLuong(),
                sp.getDonGia(),});

        }
    }//GEN-LAST:event_timKiembtnActionPerformed

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                // Tạo JFrame để chứa NhapHangJpane
                JFrame frame = new JFrame("Nhập hàng");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                // Thêm NhapHangJpane vào JFrame
                NhapHangJpane nhapHangJpane = new NhapHangJpane();
                frame.add(nhapHangJpane);

                // Cấu hình kích thước và hiển thị JFrame
                frame.setSize(1200, 700);
                frame.setLocationRelativeTo(null); // Đặt frame ở giữa màn hình
                frame.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField maPhieuTextField;
    private javax.swing.JTextField nguoiTaoPhieuTextField;
    private javax.swing.JComboBox<String> nhaCungCapcbx;
    private javax.swing.JTextField timKiemTextField;
    private javax.swing.JButton timKiembtn;
    // End of variables declaration//GEN-END:variables
}
