package baocaojava;

import DAO.ChiTietPhieuNhapDAO;
import DAO.HoaDonDAO;
import controller.KhachHangController;
import controller.SanPhamController;
import java.awt.Component;
import java.awt.FlowLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.ChiTieuPhieumodel;
import model.HoaDonmodel;
import model.sanpham;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import model.KhachHangmodel;

/**
 *
 * @author Toan
 */
public class QuanLySanPhamJpanel extends javax.swing.JPanel {

    private HashMap<String, Integer> originalQuantities = new HashMap<>();
    SanPhamController sanPhamController;
    DefaultTableModel defaultTableModel;
    DefaultTableModel defaultTableModel1;
    ChiTietPhieuNhapDAO chiTietPhieuNhapDAO;
    ChiTieuPhieumodel chiTietPhieumodel;
    HoaDonDAO hoaDonDAO;
    JPanel sanPhamPanel;
    private ArrayList<ItemSua> itemList = new ArrayList<>();

    /**
     * Creates new form QuanLySanPhamJpanel
     */
    public QuanLySanPhamJpanel() {
        initComponents();
        hoaDonDAO = new HoaDonDAO();
        sanPhamPanel = new JPanel();
        chiTietPhieuNhapDAO = new ChiTietPhieuNhapDAO();
        chiTietPhieumodel = new ChiTieuPhieumodel();
        sanPhamController = new SanPhamController();
        defaultTableModel = new DefaultTableModel();
        gioHangTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã sản phẩm");
        defaultTableModel.addColumn("Tên sản phẩm");
        defaultTableModel.addColumn("Số lượng");
        defaultTableModel.addColumn("Đơn giá");
        defaultTableModel.addColumn("Thành tiền");
        defaultTableModel1 = new DefaultTableModel();
        hoaDonTable.setModel(defaultTableModel1);
        defaultTableModel1.addColumn("Mã Hóa đơn");
        defaultTableModel1.addColumn("Mã Nhân viên");
        defaultTableModel1.addColumn("Tổng tiền");
        defaultTableModel1.addColumn("Ngày bán");
        hienThiSanPham();
        loadHoaDonTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        gioHangTable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        hoaDonTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ngayTaolable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        maKhTextField = new javax.swing.JTextField();
        teKhTextField = new javax.swing.JTextField();
        diemKhTextField = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        mahoadonJlable = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Giỏ hàng"));

        gioHangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(gioHangTable);

        jButton4.setText("Làm mới giỏ hàng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Bỏ khỏi giỏ hàng");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setText("Tạo hóa đơn");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(37, 37, 37)
                        .addComponent(jButton6)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton6)
                        .addComponent(jButton5))
                    .addComponent(jButton4)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách hóa đơn"));

        hoaDonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(hoaDonTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sản phẩm"));
        jScrollPane1.setViewportView(jTextField1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tạo hóa đơn"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin chung"));

        jLabel1.setText("Mã nhân viên:");

        ngayTaolable.setText("Ngày tạo");

        jLabel3.setText("Mã thành viên");

        jLabel4.setText("Họ tên thành viên:");

        jLabel5.setText("Điểm thành viên:");

        diemKhTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diemKhTextFieldActionPerformed(evt);
            }
        });

        jButton7.setText("Xác nhận");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Sử dụng");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel8.setText("111");

        jLabel9.setText("jLabel9");

        jLabel14.setText("Mã hóa đơn");

        mahoadonJlable.setText("mã hóa đơn");
        mahoadonJlable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                mahoadonJlableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(ngayTaolable))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(diemKhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(27, 27, 27)
                        .addComponent(mahoadonJlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(maKhTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                    .addComponent(teKhTextField))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14)
                    .addComponent(mahoadonJlable))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngayTaolable)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maKhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(teKhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(diemKhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Chi tiết"));

        jLabel6.setText("Tiền thanh toán:");

        jLabel7.setText("Giảm giá:");

        jLabel10.setText("jLabel10");

        jLabel11.setText("jLabel10");

        jLabel12.setText("Tổng tiền hàng:");

        jLabel13.setText("jLabel10");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButton3.setText("Thanh toán");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void loadHoaDonTable() {
        defaultTableModel1.setRowCount(0);
        ArrayList<HoaDonmodel> hoaDonmodels = hoaDonDAO.getIntance().selectAll();
        for (HoaDonmodel hoaDonmodel : hoaDonmodels) {
            defaultTableModel1.addRow(new Object[]{
                hoaDonmodel.getMaHD(),
                hoaDonmodel.getMaNV(),
                hoaDonmodel.getTongTien(),
                hoaDonmodel.getNgayban()
            });
        }
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int selectedRow = gioHangTable.getSelectedRow();
        if (selectedRow != -1) {
            // Lấy mã sản phẩm và số lượng từ hàng được chọn trong giỏ hàng
            String masp = gioHangTable.getValueAt(selectedRow, 0).toString();
            int quantityInCart = Integer.parseInt(gioHangTable.getValueAt(selectedRow, 2).toString()); // Giả sử cột 2 là số lượng

            // Xóa hàng khỏi giỏ hàng
            defaultTableModel.removeRow(selectedRow);

            // Tìm `ItemSua` tương ứng và cộng lại số lượng
            for (Component comp : sanPhamPanel.getComponents()) {
                if (comp instanceof ItemSua) {
                    ItemSua item = (ItemSua) comp;
                    if (item.getMaSP().equals(masp)) {
                        // Lấy số lượng hiện tại trong `ItemSua` và cộng thêm số lượng vừa xóa khỏi giỏ
                        int currentQuantity = Integer.parseInt(item.getSoLuongJlable().getText().replace("Số lượng: ", "").trim());
                        int updatedQuantity = currentQuantity + quantityInCart;
                        item.updateQuantity(updatedQuantity); // Cập nhật lại số lượng hiển thị trong `ItemSua`
                        break;
                    }
                }
            }

            JOptionPane.showMessageDialog(null, "Đã bỏ hàng khỏi giỏ!");
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng để bỏ khỏi giỏ!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void diemKhTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diemKhTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diemKhTextFieldActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void mahoadonJlableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_mahoadonJlableAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_mahoadonJlableAncestorAdded

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        mahoadonJlable.setText(CreatId());
        // Lấy thời gian hiện tại
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());

        // Định dạng timestamp thành chuỗi
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String currentTime = sdf.format(timestamp);

        // Cập nhật jLabel9 với thời gian hiện tại
        jLabel9.setText(currentTime);
        jLabel10.setText(String.valueOf(calculateTotalPrice()) + "đ");
        jLabel13.setText(String.valueOf(calculateTotalPrice()) + "đ");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (maKhTextField.getText() == "") {
            JOptionPane.showMessageDialog(this, "Vui lòng điền mã khách hàng");
        } else {
            KhachHangController khachHangController = new KhachHangController();
            KhachHangmodel khachHangmodel = khachHangController.selectById(maKhTextField.getText());
            if (khachHangmodel == null) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên");

            } else {
                teKhTextField.setText(khachHangmodel.getTenKh());
                diemKhTextField.setText(String.valueOf(khachHangmodel.getDiem()));
            }
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        // Lấy tổng tiền thanh toán
        // Lấy tổng tiền thanh toán
        // Lấy tổng tiền thanh toán
        double tienThanhToan = calculateTotalPrice();

        // Lấy điểm giảm giá từ trường điểm khách hàng
        double giamGia = Double.parseDouble(diemKhTextField.getText());
        double diemSD = 0;
        double diemconlai = 0;
        double diemKh = Double.parseDouble(diemKhTextField.getText());
        // Kiểm tra xem điểm giảm giá có lớn hơn tổng tiền thanh toán không
        if (giamGia > tienThanhToan) {
            diemSD = tienThanhToan;
            // Nếu có, đặt tổng tiền thanh toán về 0
            tienThanhToan = 0;
            // Cập nhật điểm thành viên đã sử dụng
            jLabel11.setText(String.valueOf(diemSD));
            diemconlai = diemKh - diemSD;
            diemKhTextField.setText(String.valueOf(diemconlai));

        } else {
            // Nếu không, tính toán tiền thanh toán sau khi giảm giá
            diemKhTextField.setText(String.valueOf(diemconlai));
            tienThanhToan -= giamGia;
            jLabel11.setText(String.valueOf(giamGia) + "đ"); // Hiển thị giá trị giảm giá
        }

        // Cập nhật tổng tiền thanh toán
        jLabel13.setText(String.valueOf(tienThanhToan) + "đ");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        HoaDonmodel hoaDonmodel = new HoaDonmodel();
        hoaDonmodel.setMaHD(mahoadonJlable.getText());
        hoaDonmodel.setMaKh(maKhTextField.getText());
        hoaDonmodel.setNgayban(Timestamp.valueOf(jLabel9.getText()));
        hoaDonmodel.setMaNV(jLabel8.getText());
        String cleaString = jLabel13.getText().replaceAll("[^0-9.]", "");
        hoaDonmodel.setTongTien(Double.parseDouble(cleaString));
        hoaDonDAO.getIntance().them(hoaDonmodel);
        JOptionPane.showMessageDialog(this, "thanh toán thành công");

    }//GEN-LAST:event_jButton3ActionPerformed
// Assuming you have a method that creates ItemSua instances

    public void hienThiSanPham() {
        ArrayList<sanpham> sanPhamList = sanPhamController.selectAll();
        sanPhamPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 30, 0));

        for (sanpham sanPham : sanPhamList) {
            ItemSua item = new ItemSua(this);
            item.setMaSP(sanPham.getMaSua()); // Set the product ID
            item.getTenSuaJlabel().setText(sanPham.getTenSua());
            item.getSoLuongJlable().setText("Số lượng: " + sanPham.getSoLuong());
            item.getDonGiaJlable().setText("Đơn giá: " + sanPham.getDonGia());
            item.setDuongDanAnh(sanPham.getAnh());
            // Set the icon based on the product ID
            sanPhamPanel.add(item);
        }
        sanPhamPanel.revalidate(); // Cập nhật layout
        sanPhamPanel.repaint();// Create JScrollPane for sanPhamPanel with horizontal scrolling
        JScrollPane scrollPane = new JScrollPane(sanPhamPanel, JScrollPane.VERTICAL_SCROLLBAR_NEVER, JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportView(scrollPane); // Add JScrollPane to the main JScrollPane
    }

    public void addProductToCart(String productName, int quantity, double price, String masp) {
        double totalPrice = quantity * price; // Tính toán thành tiền

        // Thêm vào bảng
        defaultTableModel.addRow(new Object[]{
            masp, // Thay bằng mã sản phẩm thực tế nếu có
            productName,
            quantity,
            price,
            totalPrice
        });
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                // Tạo khung chính
                JFrame frame = new JFrame("Quản Lý Sản Phẩm");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(800, 600);

                // Thêm JPanel vào khung
                QuanLySanPhamJpanel quanLySanPhamJpanel = new QuanLySanPhamJpanel();
                frame.add(quanLySanPhamJpanel);

                // Hiển thị khung
                frame.setVisible(true);
            }
        });
    }

    public String CreatId() {
        ArrayList<HoaDonmodel> arr = hoaDonDAO.getIntance().selectAll();
        String check = "";
        int id = arr.size() + 1;
        if (arr != null) {
            for (HoaDonmodel nhanVienmodel : arr) {
                if (nhanVienmodel.getMaHD().equals("HD" + id)) {
                    check = nhanVienmodel.getMaHD();
                }
            }
            while (check.length() != 0) {
                id++;
                for (int i = 0; i <= arr.size(); i++) {
                    if (arr.get(i).getMaHD().equals("HD" + id)) {
                        check = arr.get(i).getMaHD();
                    } else {
                        check = "";
                    }
                }
            }
            return "HD" + id;
        } else {
            return "HD" + 1;
        }
    }

    private double calculateTotalPrice() {
        double totalPrice = 0.0;

        // Lặp qua từng hàng trong bảng giỏ hàng
        for (int i = 0; i < gioHangTable.getRowCount(); i++) {
            // Giả sử cột thành tiền là cột thứ 4 (index 4)
            double itemTotalPrice = (double) gioHangTable.getValueAt(i, 4);
            totalPrice += itemTotalPrice; // Cộng dồn thành tiền
        }

        return totalPrice; // Trả về tổng tiền
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diemKhTextField;
    private javax.swing.JTable gioHangTable;
    private javax.swing.JTable hoaDonTable;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField maKhTextField;
    private javax.swing.JLabel mahoadonJlable;
    private javax.swing.JLabel ngayTaolable;
    private javax.swing.JTextField teKhTextField;
    // End of variables declaration//GEN-END:variables
}
