package baocaojava;

import controller.SanPhamController;
import javax.swing.JOptionPane;
import model.sanpham;
import javax.swing.JFileChooser;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Toan
 */
public class QuanLySanPham extends javax.swing.JPanel {

    SanPhamController sanPhamController;
    sanpham sp;
    String duongDanAnh = "D:\\hdt\\baocaojava\\src\\picture\\images.png";
    DefaultTableModel defaultTableModel;

    /**
     * Creates new form QuanLySanPham
     */
    public QuanLySanPham() {
        initComponents();
        sanPhamController = new SanPhamController();
        defaultTableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }

        };
        sanPhamTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã sản phẩm");
        defaultTableModel.addColumn("Tên sản phẩm");
        defaultTableModel.addColumn("Số lượng");
        defaultTableModel.addColumn("Đơn vị");
        defaultTableModel.addColumn("Khối lượng");
        defaultTableModel.addColumn("Đơn giá");
        defaultTableModel.addColumn("Ngày hết hạn");
        loadDataToTable();

        // Thiết lập sự kiện khi người dùng chọn hàng
        sanPhamTable.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting()) {
                updateFieldsFromSelectedRow();
            }
        });
        maSpTextFiled.setText(CreatId());
    }

    private void loadDataToTable() {
        ArrayList<sanpham> list = sanPhamController.selectAll();
        for (sanpham sp : list) {
            defaultTableModel.addRow(new Object[]{
                sp.getMaSua(),
                sp.getTenSua(),
                sp.getSoLuong(),
                sp.getSize(),
                sp.getKhoiLuong(),
                sp.getDonGia(),
                sp.getNgayHetHan()
            });

        }
    }

    public void updateFieldsFromSelectedRow() {
        int row = sanPhamTable.getSelectedRow();

        // Kiểm tra nếu hàng được chọn hợp lệ
        if (row >= 0) {
            String sp = String.valueOf(sanPhamTable.getValueAt(row, 0));
            sanpham sanPhamUD = sanPhamController.selectById(sp);

            maSpTextFiled.setText(sanPhamUD.getMaSua());
            tenSpTextField.setText(sanPhamUD.getTenSua());
            soluongSpn.setValue(sanPhamUD.getSoLuong());
            kichCocbx.setSelectedItem(sanPhamUD.getSize());
            donGiaTextField.setText(String.valueOf(sanPhamUD.getDonGia()));
            // Thiết lập giá trị cho JDateChooser
            if (sanPhamUD.getNgayHetHan() != null) {
                hanSuDungDate.setDate(sanPhamUD.getNgayHetHan());
            }
            maSpTextFiled.setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        sanPhamTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        lbAnh = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        timKiemTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        timKiemBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        maSpTextFiled = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tenSpTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hanSuDungDate = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        kichCocbx = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        khoiLuongTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        soluongSpn = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        donGiaTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        themBtn = new javax.swing.JButton();
        capnhatJbtn = new javax.swing.JButton();
        deleteJbtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        refreshjbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        sanPhamTable.setBackground(new java.awt.Color(255, 255, 255));
        sanPhamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sanPhamTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(sanPhamTable);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("QUẢN LÝ NHÂN VIÊN");

        lbAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/images.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Create.png"))); // NOI18N
        jButton1.setText("Thêm ảnh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nhập từ khóa cần tìm:");

        timKiemBtn.setBackground(new java.awt.Color(255, 153, 51));
        timKiemBtn.setForeground(new java.awt.Color(0, 0, 0));
        timKiemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search.png"))); // NOI18N
        timKiemBtn.setText("Tìm kiếm");
        timKiemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addGap(50, 50, 50)
                .addComponent(timKiemTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addGap(68, 68, 68)
                .addComponent(timKiemBtn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(timKiemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKiemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Mã sản phẩm:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Tên sản phẩm:");

        tenSpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenSpTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Hạn sử dụng:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Kích cỡ:");

        kichCocbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hộp", "Dây", "Combo" }));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Khối lượng:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Số lượng:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Số lượng:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(kichCocbx, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(hanSuDungDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(maSpTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tenSpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(soluongSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(khoiLuongTextField)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(donGiaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(maSpTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tenSpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(hanSuDungDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kichCocbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(khoiLuongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(soluongSpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(donGiaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        themBtn.setBackground(new java.awt.Color(255, 153, 51));
        themBtn.setForeground(new java.awt.Color(0, 0, 0));
        themBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Add.png"))); // NOI18N
        themBtn.setText("Thêm");
        themBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themBtnActionPerformed(evt);
            }
        });

        capnhatJbtn.setBackground(new java.awt.Color(255, 153, 51));
        capnhatJbtn.setForeground(new java.awt.Color(0, 0, 0));
        capnhatJbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Edit.png"))); // NOI18N
        capnhatJbtn.setText("Cập nhật");
        capnhatJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatJbtnActionPerformed(evt);
            }
        });

        deleteJbtn.setBackground(new java.awt.Color(255, 153, 51));
        deleteJbtn.setForeground(new java.awt.Color(0, 0, 0));
        deleteJbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Delete.png"))); // NOI18N
        deleteJbtn.setText("Xóa");
        deleteJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(themBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(capnhatJbtn)
                .addGap(24, 24, 24)
                .addComponent(deleteJbtn)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capnhatJbtn)
                    .addComponent(themBtn)
                    .addComponent(deleteJbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        jButton2.setBackground(new java.awt.Color(255, 153, 51));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Task list.png"))); // NOI18N
        jButton2.setText("Bỏ chọn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        refreshjbtn.setBackground(new java.awt.Color(255, 153, 51));
        refreshjbtn.setForeground(new java.awt.Color(0, 0, 0));
        refreshjbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Refresh.png"))); // NOI18N
        refreshjbtn.setText("Làm mới");
        refreshjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshjbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(refreshjbtn))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))))
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(451, 451, 451)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(354, 354, 354)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(64, 64, 64)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbAnh)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel10)
                    .addContainerGap(667, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void themBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themBtnActionPerformed
        // Kiểm tra nếu bất kỳ trường nào bắt buộc đều trống
        // Kiểm tra nếu bất kỳ trường nào bắt buộc đều trống
        if (maSpTextFiled.getText().trim().isEmpty()
                || tenSpTextField.getText().trim().isEmpty()
                || khoiLuongTextField.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return; // Dừng xử lý nếu bất kỳ trường nào bắt buộc đều trống
        }

        // Xác thực và phân tích ngày hết hạn
        java.util.Date selectedDate = hanSuDungDate.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày hết hạn hợp lệ!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return; // Dừng xử lý nếu ngày hết hạn không hợp lệ
        }

        // Khởi tạo đối tượng sản phẩm
        sanpham sp = new sanpham();
        java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
        sp.setNgayHetHan(sqlDate);

        String maSp = maSpTextFiled.getText().trim();
        if (sanPhamController.isMaSpExists(maSp)) {
            JOptionPane.showMessageDialog(this, "Mã sản phẩm đã tồn tại, vui lòng nhập mã khác!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return; // Dừng xử lý nếu mã sản phẩm đã được sử dụng
        }

        // Set thông tin sản phẩm vào đối tượng sanpham
        sp.setMaSua(maSp);
        sp.setTenSua(tenSpTextField.getText().trim());
        sp.setSize(kichCocbx.getSelectedItem().toString());
        sp.setSoLuong((int) soluongSpn.getValue());
        sp.setDonGia(Double.parseDouble(donGiaTextField.getText()));
        sp.setAnh(duongDanAnh);
        sp.setKhoiLuong(khoiLuongTextField.getText());

        // Thêm sản phẩm qua controller
        sanPhamController.ThemSanPham(sp);

        // Thông báo thành công
        JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_themBtnActionPerformed

    private void capnhatJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhatJbtnActionPerformed
        // TODO add your handling code here:
        int row = sanPhamTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm muốn cập nhật", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            sanpham sp = new sanpham();
            sp.setMaSua(maSpTextFiled.getText().trim());
            sp.setTenSua(tenSpTextField.getText().trim());
            sp.setSize(kichCocbx.getSelectedItem().toString());
            sp.setSoLuong((int) soluongSpn.getValue());
            sp.setDonGia(Double.parseDouble(donGiaTextField.getText()));
            sp.setAnh(duongDanAnh);

            java.util.Date selectedDate = hanSuDungDate.getDate();
            if (selectedDate != null) {
                java.sql.Date sqlDate = new java.sql.Date(selectedDate.getTime());
                sp.setNgayHetHan(sqlDate);
            }

            // Gọi controller để cập nhật sản phẩm
            sanPhamController.UpdateSanPham(sp);
            JOptionPane.showMessageDialog(this, "Cập nhật sản phẩm thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_capnhatJbtnActionPerformed

    private void deleteJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJbtnActionPerformed
        // TODO add your handling code here:
        // Kiểm tra nếu có hàng nào được chọn
        int row = sanPhamTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm muốn xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            // Xác nhận trước khi xóa
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa sản phẩm này không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                // Lấy mã sản phẩm từ hàng đã chọn
                String maSp = String.valueOf(sanPhamTable.getValueAt(row, 0));
                sanPhamController.XoaSanPham(maSp);

                // Cập nhật lại bảng sau khi xóa
                defaultTableModel.setRowCount(0);
                ArrayList<sanpham> sanPhamList = sanPhamController.selectAll();
                for (sanpham sp : sanPhamList) {
                    defaultTableModel.addRow(new Object[]{
                        sp.getMaSua(), sp.getTenSua(), sp.getSize(), sp.getMaNCC(), sp.getSoLuong(), sp.getDonGia(), sp.getNgayHetHan(), sp.getAnh()
                    });
                }

                JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteJbtnActionPerformed

    private void refreshjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjbtnActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        loadDataToTable();
    }//GEN-LAST:event_refreshjbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser f = new JFileChooser();
            f.setDialogTitle("Mở file");
            f.showOpenDialog(null);
            File ftenAnh = f.getSelectedFile();
            duongDanAnh = ftenAnh.getAbsolutePath();
            lbAnh.setIcon(ResizeImage(String.valueOf(duongDanAnh)));
            System.out.println(duongDanAnh);

        } catch (Exception ex) {
            System.out.print(" Chưa chọn ảnh");
            System.out.println(duongDanAnh);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void timKiemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemBtnActionPerformed
        // TODO add your handling code here:
        String name = timKiemTextField.getText(); // Giả sử name là "Toàn"
        String condition = "LOWER(TenSua) LIKE LOWER('%" + name + "%')";

        ArrayList<sanpham> nhanVienmodels = null;
        if (name.trim().length() == 0) {
            nhanVienmodels = sanPhamController.selectAll();
        } else {
            nhanVienmodels = sanPhamController.seLectByCondition(condition);
        }
        defaultTableModel.setRowCount(0);
        loadDataToTable();

    }//GEN-LAST:event_timKiemBtnActionPerformed

    private void tenSpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenSpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenSpTextFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        maSpTextFiled.setText("");
        tenSpTextField.setText("");
        soluongSpn.setValue(0);
        donGiaTextField.setText("");
        maSpTextFiled.setEditable(true);
        hanSuDungDate.setDate(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    public ImageIcon ResizeImage(String ImagePath) {
        ImageIcon myImage = new ImageIcon(ImagePath);
        Image img = myImage.getImage();
        Image newImg = img.getScaledInstance(lbAnh.getWidth(), lbAnh.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    public String CreatId() {
        sanPhamController = new SanPhamController();
        ArrayList<sanpham> arr = sanPhamController.selectAll();
        String check = "";
        int id = arr.size() + 1;
        if (arr != null) {
            for (sanpham nhanVienmodel : arr) {
                if (nhanVienmodel.getMaSua().equals("S" + id)) {
                    check = nhanVienmodel.getMaSua();
                }
            }
            while (check.length() != 0) {
                id++;
                for (int i = 0; i <= arr.size(); i++) {
                    if (arr.get(i).getMaSua().equals("NV" + id)) {
                        check = arr.get(i).getMaSua();
                    } else {
                        check = "";
                    }
                }
            }
            return "S" + id;
        } else {
            return "S" + 1;
        }
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame frame = new JFrame("Quản Lý Sản Phẩm");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(800, 600); // Cài đặt kích thước cho JFrame
                frame.add(new QuanLySanPham()); // Thêm JPanel QuanLySanPham vào JFrame
                frame.setLocationRelativeTo(null); // Hiển thị JFrame ở giữa màn hình
                frame.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton capnhatJbtn;
    private javax.swing.JButton deleteJbtn;
    private javax.swing.JTextField donGiaTextField;
    private com.toedter.calendar.JDateChooser hanSuDungDate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField khoiLuongTextField;
    private javax.swing.JComboBox<String> kichCocbx;
    private javax.swing.JLabel lbAnh;
    private javax.swing.JTextField maSpTextFiled;
    private javax.swing.JButton refreshjbtn;
    private javax.swing.JTable sanPhamTable;
    private javax.swing.JSpinner soluongSpn;
    private javax.swing.JTextField tenSpTextField;
    private javax.swing.JButton themBtn;
    private javax.swing.JButton timKiemBtn;
    private javax.swing.JTextField timKiemTextField;
    // End of variables declaration//GEN-END:variables
}
