package baocaojava;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Toan
 */
public class QuanLyPhieu extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyPhieu
     */
    public QuanLyPhieu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        nhapHangJpane1 = new baocaojava.NhapHangJpane();
        nhaCungCapJpane1 = new baocaojava.NhaCungCapJpane();
        danhSachPhieuNhapJpane1 = new baocaojava.danhSachPhieuNhapJpane();

        jTabbedPane1.addTab("tab2", nhapHangJpane1);
        jTabbedPane1.addTab("tab3", nhaCungCapJpane1);
        jTabbedPane1.addTab("tab1", danhSachPhieuNhapJpane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        // Chạy ứng dụng trong Event Dispatch Thread
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                // Tạo JFrame để chứa QuanLyPhieu
                JFrame frame = new JFrame("Quản Lý Phiếu");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                // Thêm panel QuanLyPhieu vào JFrame
                frame.getContentPane().add(new QuanLyPhieu());

                // Đặt kích thước và hiển thị JFrame
                frame.setSize(800, 600); // Điều chỉnh kích thước theo ý muốn
                frame.setLocationRelativeTo(null); // Hiển thị JFrame ở giữa màn hình
                frame.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private baocaojava.danhSachPhieuNhapJpane danhSachPhieuNhapJpane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private baocaojava.NhaCungCapJpane nhaCungCapJpane1;
    private baocaojava.NhapHangJpane nhapHangJpane1;
    // End of variables declaration//GEN-END:variables
}
